version: 2
mergeable:
  - when: pull_request.opened
    validate: []
    pass:
      - do: comment
        payload:
          body: Thanks for creating a pull request! A maintainer will review your changes shortly.
  - when: pull_request.*
    validate:
      - do: description
        no_empty:
          enabled: true
          message: Please, provide for us an awesome description to your PR 🤝
      - do: dependent
        changed:
          file: '*'
          required: ['CHANGELOG.md']
  - when: schedule.repository
    validate:
      - do: stale
        days: 3
        type: pull_request, issues
    pass:
      - do: comment
        payload:
          body: It looks old 🕰️
